{
    'name': 'Odoo 20 Budget Management',
    'author': 'Odoo Mates, Odoo SA',
    'category': 'Accounting',
    'version': '2.2.1',
    'description': """Use budgets to compare actual with expected revenues and costs""",
    'summary': 'Odoo 20 Budget Management',
    'sequence': 10,
    'depends': ['account'],
    'license': 'LGPL-3',
    'data': [
        'security/ir.access.csv',
        'data/ir_cron.xml',
        'data/mail_data.xml',
        'views/account_analytic_account_views.xml',
        'views/account_budget_views.xml',
        'wizard/account_budget_wizard_views.xml',
        'views/res_config_settings_views.xml',
        'views/account_move_views.xml',
        'report/budget_report.xml',
    ],
    'images': ['static/description/banner.gif'],
    'demo': ['data/account_budget_demo.xml'],
}
