{
    'name': 'Odoo 19 Fiscal Year & Lock Date',
    'version': '1.1.0',
    'category': 'Accounting',
    'summary': 'Odoo 19 Fiscal Year, Year-End Closing, Period Closing, Lock Date in Odoo 19',
    'description': 'Odoo 19 Fiscal Year, Fiscal Year in Odoo 19',
    'live_test_url': 'https://www.youtube.com/watch?v=Kj4hR7_uNs4',
    'sequence': '1',
    'website': 'https://www.odoomates.tech',
    'author': 'Odoo Mates, Odoo SA',
    'maintainer': 'Odoo Mates',
    'license': 'LGPL-3',
    'support': 'odoomates@gmail.com',
    'depends': ['account', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/period_closing_task_data.xml',
        'wizard/change_lock_date.xml',
        'wizard/fiscal_year_closing.xml',
        'views/fiscal_year.xml',
        'views/period_closing.xml',
        'views/settings.xml',
    ],
    'images': ['static/description/banner.gif'],
}
