from . import hr_rule_parameter
from . import hr_salary_bracket
from . import hr_salary_component
from . import hr_contract
from . import hr_employee
from . import res_config_settings
from . import hr_salary_rule
from . import hr_payslip
from . import resource_mixin
