from . import test_access_profile
from . import test_http
from . import test_app_wizard
from . import test_presets
from . import test_assign
from . import test_templates
from . import test_field_guard
from . import test_allowed
from . import test_menus_chatter
from . import test_history_transfer
from . import test_sign_in
from . import test_review
