{
    'name': 'Odoo 19 Recurring Payment',
    'author': 'Odoo Mates',
    'category': 'Accounting',
    'version': '1.1.0',
    'description': """Odoo 19 Recurring Payment, Recurring Payment In Odoo, Odoo 19 Accounting""",
    'summary': 'Use recurring payments to handle periodically repeated payments',
    'sequence': 11,
    'website': 'https://www.odoomates.tech',
    'depends': ['account', 'mail'],
    'license': 'LGPL-3',
    'data': [
        'data/sequence.xml',
        'data/recurring_cron.xml',
        'data/mail_activity_type_data.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/recurring_template_view.xml',
        'views/recurring_payment_view.xml',
        'views/auto_post_views.xml',
    ],
    'images': ['static/description/banner.png'],
}
