# -*- coding: utf-8 -*-

{
    'name': 'Odoo 14 Standard Accounting Report',
    'version': '14.0.1.0.0',
    'category': 'Accounting',
    'author': 'Florent de Labarre, Odoo Mates, Odoo Community Association (OCA)',
    'summary': 'Standard Accounting Report',
    'website': '',
    'depends': ['account'],
    'data': [
        'security/ir.model.access.csv',
        'data/report_paperformat.xml',
        'data/data_account_standard_report.xml',
        'data/res_currency_data.xml',
        'views/webclient_templates.xml',
        'report/report_account_standard_report.xml',
        'views/account_view.xml',
        'views/account_standard.xml',
        'views/account_standard_report_template_view.xml',
        'views/res_currency_views.xml',
        'wizard/account_standard_report_view.xml',
    ],
    'demo': [],
    'external_dependencies': {"python": ["xlsxwriter", "xlrd"]},
    'license': 'LGPL-3',
    'support': '',
    'installable': True,
    'auto_install': False,
    'images': ['images/main_screenshot.png'],
}
