{
    'name': 'User Audit & Sessions',
    'version': '0.9.0',
    'author': 'Odoo Mates',
    'category': 'Tools',
    'description': 'Who signed in, from where, and what they read, changed, exported, imported and printed; the open sessions, ended in one click. Beta.',
    'summary': 'User Activity Log, Audit Trail, Login History, Active Sessions, Kill Session, Idle Timeout, Sign-in Alerts, Export Log',
    'maintainer': 'Odoo Mates',
    'support': 'odoomates@gmail.com',
    'license': 'LGPL-3',
    'depends': ['base', 'web', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'data/mail_template.xml',
        'report/om_user_audit_report.xml',
        'views/om_user_audit_log_views.xml',
        'views/om_user_audit_rule_views.xml',
        'views/om_user_audit_session_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_users_views.xml',
        'wizard/om_user_audit_report_wizard_views.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/banner.gif'],
}
