{
    'name': 'Customer Follow Up Management',
    'version': '16.0.1.1.0',
    'category': 'Accounting',
    'description': """Customer payment follow-ups: reminders by email and letter, customer statements, promises to pay
and disputed invoices.""",
    'summary': """Customer payment follow-ups and reminders""",
    'author': 'Odoo Mates, Odoo S.A',
    'license': 'LGPL-3',
    'website': 'https://www.odoomates.tech',
    'depends': ['account', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/mail_activity_type_data.xml',
        'data/ir_cron.xml',
        'wizard/followup_print_view.xml',
        'wizard/followup_results_view.xml',
        'wizard/followup_send_views.xml',
        'views/followup_view.xml',
        'views/account_move.xml',
        'views/partners.xml',
        'views/report_followup.xml',
        'views/reports.xml',
        'views/followup_partner_view.xml',
        'report/report_style.xml',
        'report/customer_statement.xml',
        'report/followup_report.xml',
        'data/mail_template_statement_data.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'demo': ['demo/demo.xml'],
    'images': ['static/description/banner.gif'],
}
