{
    'name': 'Customer Follow Up Management',
    'version': '1.1.0',
    'category': 'Accounting',
    'description': """Customer payment follow-ups: reminders by email and letter, customer statements, promises to pay,
disputed invoices and follow-up plans per customer.""",
    'summary': """Customer payment follow-ups and reminders""",
    'author': 'Odoo Mates, Odoo S.A',
    'license': 'LGPL-3',
    'depends': ['account', 'mail'],
    'data': [
        'security/ir.access.csv',
        'data/mail_template_data.xml',
        'data/mail_activity_type_data.xml',
        'data/ir_cron.xml',
        'wizard/followup_print_view.xml',
        'wizard/followup_results_view.xml',
        'wizard/followup_send_views.xml',
        'views/followup_view.xml',
        'views/account_move.xml',
        'views/partners.xml',
        'views/followup_partner_view.xml',
        'report/customer_statement.xml',
        'report/followup_report.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'demo': ['demo/demo.xml'],
    'images': ['static/description/banner.png'],
}
